import React from 'react';

interface HowToPlayModalProps {
  onClose: () => void;
}

export const HowToPlayModal: React.FC<HowToPlayModalProps> = ({ onClose }) => {
  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4 z-50 animate-fade-in">
      <div className="pixel-card max-w-md w-full max-h-[90vh] overflow-y-auto animate-pop-in">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b-2 border-gray-800">
          <h2 className="text-2xl font-bold" style={{ color: 'var(--color-primary)' }}>
            How to Play
          </h2>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 text-3xl font-bold leading-none"
            aria-label="Close"
          >
            ×
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          {/* Step 1 */}
          <div className="flex items-start gap-4">
            <div 
              className="w-14 h-14 rounded-lg flex items-center justify-center flex-shrink-0 border-2 border-gray-800"
              style={{ backgroundColor: 'var(--color-accent)' }}
            >
              <span className="text-3xl">👀</span>
            </div>
            <div>
              <h3 className="font-bold text-lg mb-2" style={{ color: 'var(--color-dark)' }}>
                Look Carefully
              </h3>
              <p className="text-gray-600 text-sm">
                Examine each image closely. Look for unnatural textures, 
                impossible lighting, or subtle artifacts.
              </p>
            </div>
          </div>

          {/* Step 2 */}
          <div className="flex items-start gap-4">
            <div 
              className="w-14 h-14 rounded-lg flex items-center justify-center flex-shrink-0 border-2 border-gray-800"
              style={{ backgroundColor: 'var(--color-secondary)' }}
            >
              <span className="text-3xl">🤔</span>
            </div>
            <div>
              <h3 className="font-bold text-lg mb-2" style={{ color: 'var(--color-dark)' }}>
                Make Your Choice
              </h3>
              <p className="text-gray-600 text-sm">
                Decide whether the image is a real photograph or generated by AI. 
                Trust your instincts!
              </p>
            </div>
          </div>

          {/* Step 3 */}
          <div className="flex items-start gap-4">
            <div 
              className="w-14 h-14 rounded-lg flex items-center justify-center flex-shrink-0 border-2 border-gray-800"
              style={{ backgroundColor: 'var(--color-success)' }}
            >
              <span className="text-3xl">🏆</span>
            </div>
            <div>
              <h3 className="font-bold text-lg mb-2" style={{ color: 'var(--color-dark)' }}>
                Compete & Learn
              </h3>
              <p className="text-gray-600 text-sm">
                See your score and compare with other players on the leaderboard. 
                Learn from each challenge!
              </p>
            </div>
          </div>

          {/* Tips */}
          <div 
            className="p-4 rounded-lg border-2 border-gray-800"
            style={{ backgroundColor: 'var(--color-warning)' }}
          >
            <h4 className="font-bold mb-3 flex items-center gap-2" style={{ color: 'var(--color-dark)' }}>
              <span className="text-xl">💡</span>
              Pro Tips
            </h4>
            <ul className="text-sm space-y-2" style={{ color: 'var(--color-dark)' }}>
              <li className="flex items-start gap-2">
                <span className="font-bold">•</span>
                <span>Look for inconsistent lighting and shadows</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="font-bold">•</span>
                <span>Check for unnatural skin textures or eyes</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="font-bold">•</span>
                <span>Notice impossible architectural details</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="font-bold">•</span>
                <span>Trust your gut feeling!</span>
              </li>
            </ul>
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t-2 border-gray-800">
          <button
            onClick={onClose}
            className="pixel-button w-full text-white font-bold py-4 px-6 rounded-lg text-lg"
            style={{ backgroundColor: 'var(--color-primary)' }}
          >
            Got it! Let's Play
          </button>
        </div>
      </div>
    </div>
  );
};
